import { defineStore } from "pinia";

export const usePlayersListStore = defineStore("playersListStore", {
	state: () => ({
		teams: [],
		tournamentPlayers: [
			{ name: "Scottie Scheffler" },
			{ name: "Rory McIlroy" },
			{ name: "Bryson DeChambeau" },
			{ name: "Jon Rahm" },
			{ name: "Xander Schauffele" },
			{ name: "Collin Morikawa" },
			{ name: "Joaquin Niemann" },
			{ name: "Tommy Fleetwood" },
			{ name: "Ludvig Aberg" },
			{ name: "Justin Thomas" },
			{ name: "Tyrrell Hatton" },
			{ name: "Shane Lowry" },
			{ name: "Sepp Straka" },
			{ name: "Patrick Cantlay" },
			{ name: "Brooks Koepka" },
			{ name: "Corey Conners" },
			{ name: "Viktor Hovland" },
			{ name: "Russell Henley" },
			{ name: "Ben Griffin" },
			{ name: "Jordan Spieth" },
			{ name: "Hideki Matsuyama" },
			{ name: "Sam Burns" },
			{ name: "Daniel Berger" },
			{ name: "Aaron Rai" },
			{ name: "Tony Finau" },
			{ name: "Patrick Reed" },
			{ name: "Keegan Bradley" },
			{ name: "Harris English" },
			{ name: "Si Woo Kim" },
			{ name: "Robert MacIntyre" },
			{ name: "Maverick McNealy" },
			{ name: "Justin Rose" },
			{ name: "Denny McCarthy" },
			{ name: "Taylor Pendrith" },
			{ name: "Sungjae Im" },
			{ name: "J.J. Spaun" },
			{ name: "Matt Fitzpatrick" },
			{ name: "Jason Day" },
			{ name: "Cameron Young" },
			{ name: "Cameron Smith" },
			{ name: "Thorbjorn Olesen" },
			{ name: "Wyndham Clark" },
			{ name: "Akshay Bhatia" },
			{ name: "J.T Poston" },
			{ name: "Brian Harman" },
			{ name: "Adam Scott" },
			{ name: "Nick Taylor" },
			{ name: "Min Woo Lee" },
			{ name: "Andrew Novak" },
			{ name: "Dustin Johnson" },
			{ name: "Ryan Fox" },
			{ name: "Eric Cole" },
			{ name: "Carlos Ortiz" },
			{ name: "Ryan Gerard" },
			{ name: "Rasmus Neergaard-Petersen" },
			{ name: "Marc Leishman" },
			{ name: "Bud Cauley" },
			{ name: "Tom Kim" },
			{ name: "Mackenzie Hughes" },
			{ name: "Lucas Glover" },
			{ name: "Michael Kim" },
			{ name: "Gary Woodland" },
			{ name: "Davis Thompson" },
			{ name: "Christiaan Bezuidenhout" },
			{ name: "Byeong Hun An" },
			{ name: "Max Greyserman" },
			{ name: "Jackson Koivun" },
			{ name: "Sam Stevens" },
			{ name: "Tom Hoge" },
			{ name: "Thomas Detry" },
			{ name: "Stephan Jaeger" },
			{ name: "Jacob Bridgeman" },
			{ name: "Rasmus Hojgaard" },
			{ name: "Matt Wallace" },
			{ name: "Phil Mickelson" },
			{ name: "Davis Riley" },
			{ name: "Jhonattan Vegas" },
			{ name: "Jordan Smith" },
			{ name: "Erik Van Rooyen" },
			{ name: "John Keefer" },
			{ name: "Niklas Norgaard" },
			{ name: "Matthieu Pavon" },
			{ name: "Chris Kirk" },
			{ name: "Cam Davis" },
			{ name: "Nico Echavarria" },
			{ name: "Laurie Canter" },
			{ name: "Emiliano Grillo" },
			{ name: "Victor Perez" },
			{ name: "Mark Hubbard" },
			{ name: "Matt McCarty" },
			{ name: "Richard Bland" },
			{ name: "Chris Gotterup" },
			{ name: "Ben James" },
			{ name: "Matthew Jordan" },
			{ name: "Michael La Sasso" },
			{ name: "Edoardo Molinari" },
			{ name: "Joe Highsmith" },
			{ name: "Jinichiro Kozuma" },
			{ name: "Dug Ghim" },
			{ name: "Justin Lower" },
			{ name: "Sam Bairstow" },
			{ name: "Zach Bauchou" },
			{ name: "Brian Campbell" },
			{ name: "Emilio Gonzalez" },
			{ name: "Chandler Blanchet" },
			{ name: "Alistair Docherty" },
			{ name: "Kevin Velo" },
			{ name: "Adam Schenk" },
			{ name: "Lanto Griffin" },
			{ name: "Justin Hastings" },
			{ name: "Andrea Pavan" },
			{ name: "Thriston Lawrence" },
			{ name: "Preston Summerhays" },
			{ name: "Jackson Buchanan" },
			{ name: "Alvaro Ortiz" },
			{ name: "Jacques Kruyswijk" },
			{ name: "Nick Dunlap" },
			{ name: "Frederic Lacroix" },
			{ name: "Guido Migliozzi" },
			{ name: "Jose Luis Ballester" },
			{ name: "Scott Vincent" },
			{ name: "Zac Blair" },
			{ name: "Ryan McCormick" },
			{ name: "Lance Simpson" },
			{ name: "Cameron Tankersley" },
			{ name: "Tyler Weaver" },
			{ name: "Bryan Lee" },
			{ name: "Chase Johnson" },
			{ name: "Takumi Kanaya" },
			{ name: "Riki Kawamoto" },
			{ name: "Evan Beck" },
			{ name: "Zach Pollo" },
			{ name: "Yuta Sugiura" },
			{ name: "Trent Phillips" },
			{ name: "Frankie Harris" },
			{ name: "Matt Vogt" },
			{ name: "James Nicholas" },
			{ name: "Mason Howell" },
			{ name: "Philip Barbaree" },
			{ name: "Joey Herrera" },
			{ name: "Trevor Gutschewski" },
			{ name: "Trevor Cone" },
			{ name: "Roberto Diaz" },
			{ name: "Maxwell Moldovan" },
			{ name: "Will Chandler" },
			{ name: "Riley Lewis" },
			{ name: "George Duangmanee" },
			{ name: "Joakim Lagergren" },
			{ name: "Brady Calkins" },
			{ name: "Noah Kent" },
			{ name: "James Hahn" },
			{ name: "Grant Haefner" },
			{ name: "Harrison Ott" },
			{ name: "George Kneiser" },
			{ name: "Justin Hicks" },
			{ name: "Austen Truslow" },
		],
	}),
	actions: {
		async fetchTeams() {
			try {
				const response = await fetch("/teams-data-usopen.json");
				const data = await response.json();
				this.teams = data.teams;
			} catch (error) {
				console.error("Error fetching teams data:", error);
			}
		},
	},
});
