import { defineStore } from "pinia";

export const usePlayersListStore = defineStore("playersListStore", {
	state: () => ({
		teams: [],
		tournamentPlayers: [
			{ name: "Scottie Scheffler" },
			{ name: "Rory McIlroy" },
			{ name: "Bryson DeChambeau" },
			{ name: "Jon Rahm" },
			{ name: "Xander Schauffele" },
			{ name: "Viktor Hovland" },
			{ name: "Ludvig Aberg" },
			{ name: "Justin Thomas" },
			{ name: "Collin Morikawa" },
			{ name: "Joaquin Niemann" },
			{ name: "Brooks Koepka" },
			{ name: "Tyrrell Hatton" },
			{ name: "Hideki Matsuyama" },
			{ name: "Tommy Fleetwood" },
			{ name: "Patrick Cantlay" },
			{ name: "Jordan Spieth" },
			{ name: "Shane Lowry" },
			{ name: "Sepp Straka" },
			{ name: "Corey Conners" },
			{ name: "Russell Henley" },
			{ name: "Jason Day" },
			{ name: "Wyndham Clark" },
			{ name: "Sungjae Im" },
			{ name: "Sergio Garcia" },
			{ name: "Patrick Reed" },
			{ name: "Min Woo Lee" },
			{ name: "Justin Rose" },
			{ name: "Robert MacIntyre" },
			{ name: "Dustin Johnson" },
			{ name: "Daniel Berger" },
			{ name: "David Puig" },
			{ name: "Tony Finau" },
			{ name: "Si Woo Kim" },
			{ name: "Maverick McNealy" },
			{ name: "Keegan Bradley" },
			{ name: "Cameron Smith" },
			{ name: "Sam Burns" },
			{ name: "Dean Burmester" },
			{ name: "Byeong Hun An" },
			{ name: "Will Zalatoris" },
			{ name: "Taylor Pendrith" },
			{ name: "Akshay Bhatia" },
			{ name: "Tom Kim" },
			{ name: "Michael Kim" },
			{ name: "J.J. Spaun" },
			{ name: "Max Homa" },
			{ name: "Keith Mitchell" },
			{ name: "Denny McCarthy" },
			{ name: "Brian Harman" },
			{ name: "Aaron Rai" },
			{ name: "Sahith Theegala" },
			{ name: "Davis Thompson" },
			{ name: "Andrew Novak" },
			{ name: "Matt Fitzpatrick" },
			{ name: "Harris English" },
			{ name: "Adam Scott" },
			{ name: "Samuel Stevens" },
			{ name: "Thomas Detry" },
			{ name: "Taylor Moore" },
			{ name: "Stephan Jaeger" },
			{ name: "Max Greyserman" },
			{ name: "Ryan Fox" },
			{ name: "Rickie Fowler" },
			{ name: "Rasmus Hojgaard" },
			{ name: "Bud Cauley" },
			{ name: "Ben Griffin" },
			{ name: "Mackenzie Hughes" },
			{ name: "Lucas Glover" },
			{ name: "Kurt Kitayama" },
			{ name: "Niklas Norgaard" },
			{ name: "J.T. Poston" },
			{ name: "Gary Woodland" },
			{ name: "Thorbjorn Olesen" },
			{ name: "Seamus Power" },
			{ name: "Tom Hoge" },
			{ name: "Rasmus Neergaard-Petersen" },
			{ name: "Nicolai Hojgaard" },
			{ name: "Jake Knapp" },
			{ name: "Tom McKibbin" },
			{ name: "Erik Van Rooyen" },
			{ name: "Cameron Young" },
			{ name: "Ryan Gerard" },
			{ name: "Nick Taylor" },
			{ name: "Kevin Yu" },
			{ name: "Jacob Bridgeman" },
			{ name: "Phil Mickelson" },
			{ name: "Patrick Rodgers" },
			{ name: "Chris Kirk" },
			{ name: "Lee Hodges" },
			{ name: "Laurie Canter" },
			{ name: "Harry Hall" },
			{ name: "Eric Cole" },
			{ name: "Rico Hoey" },
			{ name: "Alex Noren" },
			{ name: "Matt McCarty" },
			{ name: "Eugenio Chacarra" },
			{ name: "Matt Wallace" },
			{ name: "Christiaan Bezuidenhout" },
			{ name: "Cam Davis" },
			{ name: "Elvis Smylie" },
			{ name: "Austin Eckroat" },
			{ name: "Ryo Hisatsune" },
			{ name: "Keita Nakajima" },
			{ name: "Garrick Higgo" },
			{ name: "Beau Hossler" },
			{ name: "Patrick Fishburn" },
			{ name: "Joe Highsmith" },
			{ name: "Jhonattan Vegas" },
			{ name: "Sami Valimaki" },
			{ name: "Davis Riley" },
			{ name: "Karl Vilips" },
			{ name: "Nico Echavarria" },
			{ name: "Max McGreevy" },
			{ name: "Michael Thorbjornsen" },
			{ name: "Adam Hadwin" },
			{ name: "Richard Bland" },
			{ name: "Justin Lower" },
			{ name: "Marco Penge" },
			{ name: "John Parry" },
			{ name: "Nick Dunlap" },
			{ name: "Takumi Kanaya" },
			{ name: "John Catlin" },
			{ name: "Daniel van Tonder" },
			{ name: "Matthieu Pavon" },
			{ name: "Thriston Lawrence" },
			{ name: "Rafael Campos" },
			{ name: "Patton Kizzire" },
			{ name: "Padraig Harrington" },
			{ name: "John Keefer" },
			{ name: "Jason Dufner" },
			{ name: "Brian Campbell" },
			{ name: "Martin Kaymer" },
			{ name: "Luke Donald" },
			{ name: "Jimmy Walker" },
			{ name: "Andre Chi" },
			{ name: "Tyler Collet" },
			{ name: "Shaun Micheel" },
			{ name: "Justin Hicks" },
			{ name: "Greg Koch" },
			{ name: "Timothy Wiseman" },
			{ name: "Tom Johnson" },
			{ name: "Larkin Gross" },
			{ name: "John Somers" },
			{ name: "Jesse Droemer" },
			{ name: "Bob Sowards" },
			{ name: "Ryan Lenahan" },
			{ name: "Rupe Taylor" },
			{ name: "Nic Ishee" },
			{ name: "Michael Kartrude" },
			{ name: "Eric Steger" },
			{ name: "Dylan Newman" },
			{ name: "Brian Bergstol" },
			{ name: "Brandon Bingaman" },
			{ name: "Bobby Gates" },
			{ name: "Michael Block" },
			{ name: "Vjay Singh" },
		],
	}),
	actions: {
		async fetchTeams() {
			try {
				const response = await fetch("/teams-data.json");
				const data = await response.json();
				this.teams = data.teams;
			} catch (error) {
				console.error("Error fetching teams data:", error);
			}
		},
	},
});
